### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by i8sigmapi** [jpmac26/DRV3-Sharp#3]
I'd love to use these tools for their intended purpose, but I can't figure out how to run them. Do you think you could provide a guide in the readme for run instructions and a rundown of the tools' purposes?

As a side note, the Jenkins server requires a login that I have no idea how one would acquire in order to access, so if you could explain how to get into it I'd be extremely grateful.

**Comment by CaptainSwag101** [comment]
Hi there, apologies for the very late reply. These tools are intended to be run from the command line, such as the Linux terminal or Windows Command Prompt/PowerShell. You can usually just drag and drop files ending in the proper extension onto the given tool in most cases. You will, however, need to extract the CPK archives that the game ships with in order to access said data, I recommend using a tool like YACpkTool or CriPakGUI.

As for the Jenkins server, I have removed the link from the readme because my friend who was hosting it had a server failure so the link no longer works. Additionally, it was only providing builds for Linux and therefore was probably not useful to most people anyways.

As for why I don't make a how-to or set of instructions... well, frankly it's because I'm constantly rewriting these tools and have changed how they work drastically several times. These tools are by no means stable (I'm currently working on the second major overhaul as I write this, which will COMPLETELY change how they're structured and how they will be invoked), so I can't easily provide a good guide for other people to use them when I myself still haven't decided on how they should be used.

I know that's probably not an entirely satisfactory answer, but I'm a largely self-taught programmer who's figuring out how to do all this as I go along. I'm working on the code and underlying research in my spare time between university, work, and the rest of my personal life. I create these tools and libraries in the hopes that others may find them useful and to provide some sort of documentation for my research, but their primary focus at this time is to help myself research and understand Danganronpa V3 and its data.

I do intend to find an end result that should be much more user-friendly (a GUI frontend that I intend to call FlashbackLight which will provide a nice interface for interacting with these tools), but I have no estimate on when that will be ready, as it inherently relies on these tools and their research to be in a place I'm happy with.

I'll probably put a statement like this in the readme shortly after replying to you here, so that I can hopefully clarify this question for anyone else who might have it. I think it's a perfectly valid thing to ask, and while I know not everyone will like the answer, it's really the only one I can provide.
